DECLARE @MINIDEN INT
SET @MINIDEN = (SELECT MIN([Identificator]) FROM [HFWDB].[dbo].[Employers])
IF @MINIDEN > 50000 AND @MINIDEN < 60000 BEGIN SET @MINIDEN=@MINIDEN END ELSE BEGIN PRINT CONCAT(N'Минимальный идентификатор = ', @MINIDEN) END